# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fff4b49ad1d5a97418b6e3adbb7a13994d4376b2888d2ee7c7468a18d0964b290662ecf6dc67bd4194e257c145a48b881c7aa1ba91a2631ce665ae1f13fa29f

test:
  secret_key_base: 8f72aa3ae5ab642828d837e6994eda5672b77eeaa4e935178beaf1690bbef033c6877c981a80254c66a3b41509dd2f3144e547453fa75164799fd343b3b3b122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
